name: wishes_tracer

services:
    db:
        image: postgres:15-alpine
        container_name: wishes_tracer_db
        environment:
            - POSTGRES_DB=wishes_tracer
            - POSTGRES_USER=wt_admin
            - POSTGRES_PASSWORD=wt_@dm1n
        ports:
            - "5433:5432"
        volumes:
            - wishes_tracer_db_data:/var/lib/postgresql/data
                
    cache:
        image: redis:8.2.0-alpine
        container_name: wishes_tracer_cache
        ports:
            - '6378:6379'
        command: redis-server --save 20 1 --loglevel warning
        volumes:
            - wishes_tracer_redis_cache:/data

volumes:
    wishes_tracer_db_data:
    wishes_tracer_redis_cache:
